import Head from "next/head"

const Header = () => {
    return (
        <div>
            <Head>
                <title>GamesID App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
            </Head>
            <div>
                <h1 className="text-center">GamesID</h1>
            </div>
        </div>
    )
}

export default Header;